shared:
  property: "This is shared across all services"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # 100% запитів будуть трасуватися
tracing:
  observation:
    enabled: true
  propagation:
    type: w3c
logging:
  pattern:
    level: "[%X{traceId:-}] %5p"
