shared:
  property: "This is shared across all services"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  sleuth:
    tracer:
      enabled: true
    propagation:
      type: w3c