shared:
  property: "This is shared across all services"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    enabled: true
tracing:
  observation:
    enabled: true
  propagation:
    type: w3c